#! /bin/sh
#
# Tiny startup wrapper for Eclipse
#
# Copyright (c) 2004, Karl Trygve Kalleberg <karltk@gentoo.org>
# Copyright (c) 2007-2008, Jean-Noël Rivasseau <elvanor@gentoo.org>
# Copyright (c) 2004-2016, Gentoo Foundation
#
# Licensed under the GNU General Public License, version 2
#

SLOT="%SLOT%"

[ -f "/etc/eclipserc-bin-${SLOT}" ] && . "/etc/eclipserc-bin-${SLOT}"
[ -f "$HOME/gentoo/.eclipserc" ] && . "$HOME/gentoo/.eclipserc"

ECLIPSE_HOME=${ECLIPSE_HOME:="/opt/eclipse-cpp-bin-%SLOT%"}
ECLIPSE_BIN="${ECLIPSE_HOME}/eclipse"

VMS=(
	/opt/openjdk-bin-11/bin/java
	/usr/lib64/openjdk-11/bin/java
	/usr/lib/openjdk-11/bin/java
)

VM_BIN=""
for JVM in "${VMS[@]}"; do
	[ -x "$JVM" ] && VM_BIN="$JVM" && break
done

if [ ! -x "${ECLIPSE_BIN}" ] ; then
	echo "Failed to find executable '${ECLIPSE_BIN}'" > /dev/stderr
	exit 1
fi

if [ $(id -u) -eq 0 ] ; then
	echo "Do not run eclipse as root user! Exiting ..." > /dev/stderr
	exit 1
fi

[ -n "${ECLIPSE_XMS}" ] && VM_ARGS="${VM_ARGS} -Xms${ECLIPSE_XMS}"
[ -n "${ECLIPSE_XMX}" ] && VM_ARGS="${VM_ARGS} -Xmx${ECLIPSE_XMX}"
[ -n "${ECLIPSE_PERMSIZE}" ] && VM_ARGS="${VM_ARGS} -XX:PermSize=${ECLIPSE_PERMSIZE}"
[ -n "${ECLIPSE_MAX_PERMSIZE}" ] && VM_ARGS="${VM_ARGS} -XX:MaxPermSize=${ECLIPSE_MAX_PERMSIZE}"

exec "${ECLIPSE_BIN}" -vm "${VM_BIN}" "$@" ${ECLIPSE_USER_ARGS} -vmargs ${VM_ARGS}
#--launcher.GTK_version ${GTK_VERSION}
